=begin
#Namf_Communication

#AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

The version of the OpenAPI document: 1.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class AccessType
    N3_GPP_ACCESS = "3GPP_ACCESS".freeze
    NON_3_GPP_ACCESS = "NON_3GPP_ACCESS".freeze

    def self.all_vars
      @all_vars ||= [N3_GPP_ACCESS, NON_3_GPP_ACCESS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AccessType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AccessType"
    end
  end
end
