# frozen_string_literal: true

# #Namf_Communication
#
# AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
#
# The version of the OpenAPI document: 1.0.2
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.1.0-SNAPSHOT
#

$LOAD_PATH.push File.expand_path('lib', __dir__)
require 'ran-core-5g-client/version'

Gem::Specification.new do |s|
  s.name        = 'ran-core-5g-client'
  s.version     = Core5g::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['OpenAPI-Generator']
  s.email       = ['']
  s.homepage    = 'https://github.com/isimluk/ran-core-5g-client'
  s.summary     = 'Client libraries for communicating with RAN 5g Core'
  s.description = 'This gem is automatically documented by its own code'
  s.required_ruby_version = '>= 2.7'

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.executables   = []
  s.require_paths = ['lib']
  s.metadata['rubygems_mfa_required'] = 'true'
end
