# frozen_string_literal: true

# #Namf_EventExposure
#
# AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
#
# The version of the OpenAPI document: 1.3.0-alpha.3
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.1.0-SNAPSHOT
#

require 'date'
require 'time'

module Core5g
  class AccessType
    N3_GPP_ACCESS = '3GPP_ACCESS'
    NON_3_GPP_ACCESS = 'NON_3GPP_ACCESS'

    def self.all_vars
      @all_vars ||= [N3_GPP_ACCESS, NON_3_GPP_ACCESS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AccessType.all_vars.include?(value)

      raise "Invalid ENUM value #{value} for class #AccessType"
    end
  end
end
