# frozen_string_literal: true

# #Namf_Communication
#
# AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
#
# The version of the OpenAPI document: 1.0.2
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.1.0-SNAPSHOT
#

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/access_type'
require 'openapi_client/models/allowed_nssai'
require 'openapi_client/models/allowed_snssai'
require 'openapi_client/models/ambr'
require 'openapi_client/models/amf_status_change_notification'
require 'openapi_client/models/amf_status_info'
require 'openapi_client/models/area'
require 'openapi_client/models/area_of_validity'
require 'openapi_client/models/arp'
require 'openapi_client/models/assign_ebi_data'
require 'openapi_client/models/assign_ebi_error'
require 'openapi_client/models/assign_ebi_failed'
require 'openapi_client/models/assigned_ebi_data'
require 'openapi_client/models/ciphering_algorithm'
require 'openapi_client/models/configured_snssai'
require 'openapi_client/models/core_network_type'
require 'openapi_client/models/create_ue_context201_response'
require 'openapi_client/models/create_ue_context_request'
require 'openapi_client/models/ebi_arp_mapping'
require 'openapi_client/models/ecgi'
require 'openapi_client/models/eutra_location'
require 'openapi_client/models/expected_ue_behavior'
require 'openapi_client/models/gnb_id'
require 'openapi_client/models/global_ran_node_id'
require 'openapi_client/models/guami'
require 'openapi_client/models/integrity_algorithm'
require 'openapi_client/models/invalid_param'
require 'openapi_client/models/ipv6_addr'
require 'openapi_client/models/key_amf'
require 'openapi_client/models/key_amf_type'
require 'openapi_client/models/mm_context'
require 'openapi_client/models/n1_message_class'
require 'openapi_client/models/n1_message_container'
require 'openapi_client/models/n1_message_notification'
require 'openapi_client/models/n1_n2_message_transfer_cause'
require 'openapi_client/models/n1_n2_message_transfer_error'
require 'openapi_client/models/n1_n2_message_transfer_req_data'
require 'openapi_client/models/n1_n2_message_transfer_rsp_data'
require 'openapi_client/models/n1_n2_msg_txfr_err_detail'
require 'openapi_client/models/n1_n2_msg_txfr_failure_notification'
require 'openapi_client/models/n2_info_container'
require 'openapi_client/models/n2_info_content'
require 'openapi_client/models/n2_info_notification_rsp_data'
require 'openapi_client/models/n2_info_notify200_response'
require 'openapi_client/models/n2_info_notify_reason'
require 'openapi_client/models/n2_info_notify_request'
require 'openapi_client/models/n2_information_class'
require 'openapi_client/models/n2_information_notification'
require 'openapi_client/models/n2_information_transfer_error'
require 'openapi_client/models/n2_information_transfer_req_data'
require 'openapi_client/models/n2_information_transfer_result'
require 'openapi_client/models/n2_information_transfer_rsp_data'
require 'openapi_client/models/n2_ran_information'
require 'openapi_client/models/n2_sm_information'
require 'openapi_client/models/n3ga_location'
require 'openapi_client/models/nas_security_mode'
require 'openapi_client/models/ncgi'
require 'openapi_client/models/ng_ap_cause'
require 'openapi_client/models/ng_ksi'
require 'openapi_client/models/ng_ran_target_id'
require 'openapi_client/models/ngap_ie_type'
require 'openapi_client/models/non_ue_n2_info_notify_request'
require 'openapi_client/models/non_ue_n2_info_subscription_create_data'
require 'openapi_client/models/non_ue_n2_info_subscription_created_data'
require 'openapi_client/models/non_ue_n2_message_transfer_request'
require 'openapi_client/models/nr_location'
require 'openapi_client/models/nrppa_information'
require 'openapi_client/models/nsi_information'
require 'openapi_client/models/nssai_mapping'
require 'openapi_client/models/pws_error_data'
require 'openapi_client/models/pws_response_data'
require 'openapi_client/models/pdu_session_context'
require 'openapi_client/models/plmn_id'
require 'openapi_client/models/policy_req_trigger'
require 'openapi_client/models/preemption_capability'
require 'openapi_client/models/preemption_vulnerability'
require 'openapi_client/models/problem_details'
require 'openapi_client/models/pws_information'
require 'openapi_client/models/rat_selector'
require 'openapi_client/models/rat_type'
require 'openapi_client/models/ref_to_binary_data'
require 'openapi_client/models/registration_context_container'
require 'openapi_client/models/restriction_type'
require 'openapi_client/models/sc_type'
require 'openapi_client/models/seaf_data'
require 'openapi_client/models/service_area_restriction'
require 'openapi_client/models/sms_support'
require 'openapi_client/models/snssai'
require 'openapi_client/models/status_change'
require 'openapi_client/models/subscription_data'
require 'openapi_client/models/tai'
require 'openapi_client/models/transfer_reason'
require 'openapi_client/models/ue_context_release'
require 'openapi_client/models/ue_context_transfer200_response'
require 'openapi_client/models/ue_context_transfer_request'
require 'openapi_client/models/ue_context'
require 'openapi_client/models/ue_context_create_data'
require 'openapi_client/models/ue_context_create_error'
require 'openapi_client/models/ue_context_created_data'
require 'openapi_client/models/ue_context_transfer_req_data'
require 'openapi_client/models/ue_context_transfer_rsp_data'
require 'openapi_client/models/ue_context_transfer_status'
require 'openapi_client/models/ue_n1_n2_info_subscription_create_data'
require 'openapi_client/models/ue_n1_n2_info_subscription_created_data'
require 'openapi_client/models/ue_reg_status_update_req_data'
require 'openapi_client/models/ue_reg_status_update_rsp_data'
require 'openapi_client/models/user_location'

# APIs
require 'openapi_client/api/individual_subscription_document_api'
require 'openapi_client/api/individual_ue_context_document_api'
require 'openapi_client/api/n1_n2_individual_subscription_document_api'
require 'openapi_client/api/n1_n2_message_collection_document_api'
require 'openapi_client/api/n1_n2_subscriptions_collection_for_individual_ue_contexts_document_api'
require 'openapi_client/api/non_uen2_message_notification_individual_subscription_document_api'
require 'openapi_client/api/non_uen2_messages_collection_document_api'
require 'openapi_client/api/non_uen2_messages_subscriptions_collection_document_api'
require 'openapi_client/api/subscriptions_collection_document_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
