# frozen_string_literal: true

# #Namf_EventExposure
#
# AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
#
# The version of the OpenAPI document: 1.3.0-alpha.3
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.1.0-SNAPSHOT
#

# Common files
require 'ran-core-5g-client/api_client'
require 'ran-core-5g-client/api_error'
require 'ran-core-5g-client/version'
require 'ran-core-5g-client/configuration'

# Models
require 'ran-core-5g-client/models/access_state_transition_type'
require 'ran-core-5g-client/models/access_token_err'
require 'ran-core-5g-client/models/access_token_req'
require 'ran-core-5g-client/models/access_type'
require 'ran-core-5g-client/models/amf_create_event_subscription'
require 'ran-core-5g-client/models/amf_created_event_subscription'
require 'ran-core-5g-client/models/amf_event'
require 'ran-core-5g-client/models/amf_event_area'
require 'ran-core-5g-client/models/amf_event_mode'
require 'ran-core-5g-client/models/amf_event_notification'
require 'ran-core-5g-client/models/amf_event_report'
require 'ran-core-5g-client/models/amf_event_state'
require 'ran-core-5g-client/models/amf_event_subs_sync_info'
require 'ran-core-5g-client/models/amf_event_subscription'
require 'ran-core-5g-client/models/amf_event_subscription_info'
require 'ran-core-5g-client/models/amf_event_trigger'
require 'ran-core-5g-client/models/amf_event_type'
require 'ran-core-5g-client/models/amf_update_event_option_item'
require 'ran-core-5g-client/models/amf_update_event_subscription_item'
require 'ran-core-5g-client/models/amf_updated_event_subscription'
require 'ran-core-5g-client/models/buffered_notifications_action'
require 'ran-core-5g-client/models/cell_global_id'
require 'ran-core-5g-client/models/cm_info'
require 'ran-core-5g-client/models/cm_state'
require 'ran-core-5g-client/models/communication_failure'
require 'ran-core-5g-client/models/ddd_traffic_descriptor'
require 'ran-core-5g-client/models/dispersion_area'
require 'ran-core-5g-client/models/ecgi'
require 'ran-core-5g-client/models/eutra_location'
require 'ran-core-5g-client/models/ext_snssai'
require 'ran-core-5g-client/models/gnb_id'
require 'ran-core-5g-client/models/gera_location'
require 'ran-core-5g-client/models/global_ran_node_id'
require 'ran-core-5g-client/models/guami'
require 'ran-core-5g-client/models/hfc_node_id'
require 'ran-core-5g-client/models/idle_status_indication'
require 'ran-core-5g-client/models/invalid_param'
require 'ran-core-5g-client/models/ipv6_addr'
require 'ran-core-5g-client/models/ladn_info'
require 'ran-core-5g-client/models/line_type'
require 'ran-core-5g-client/models/location_area_id'
require 'ran-core-5g-client/models/location_filter'
require 'ran-core-5g-client/models/loss_of_connectivity_reason'
require 'ran-core-5g-client/models/mm_transaction_location_report_item'
require 'ran-core-5g-client/models/mm_transaction_slice_report_item'
require 'ran-core-5g-client/models/model5_gs_user_state'
require 'ran-core-5g-client/models/model5_gs_user_state_info'
require 'ran-core-5g-client/models/modify_subscription_request'
require 'ran-core-5g-client/models/muting_exception_instructions'
require 'ran-core-5g-client/models/muting_notifications_settings'
require 'ran-core-5g-client/models/n3ga_location'
require 'ran-core-5g-client/models/nf_type'
require 'ran-core-5g-client/models/ncgi'
require 'ran-core-5g-client/models/ng_ap_cause'
require 'ran-core-5g-client/models/notification_flag'
require 'ran-core-5g-client/models/nr_location'
require 'ran-core-5g-client/models/partitioning_criteria'
require 'ran-core-5g-client/models/plmn_id'
require 'ran-core-5g-client/models/plmn_id_nid'
require 'ran-core-5g-client/models/presence_info'
require 'ran-core-5g-client/models/presence_state'
require 'ran-core-5g-client/models/problem_details'
require 'ran-core-5g-client/models/reachability_filter'
require 'ran-core-5g-client/models/redirect_response'
require 'ran-core-5g-client/models/rm_info'
require 'ran-core-5g-client/models/rm_state'
require 'ran-core-5g-client/models/routing_area_id'
require 'ran-core-5g-client/models/sd_range'
require 'ran-core-5g-client/models/service_area_id'
require 'ran-core-5g-client/models/snssai'
require 'ran-core-5g-client/models/snssai_extension'
require 'ran-core-5g-client/models/snssai_tai_mapping'
require 'ran-core-5g-client/models/sub_termination_reason'
require 'ran-core-5g-client/models/subscription_action'
require 'ran-core-5g-client/models/supported_snssai'
require 'ran-core-5g-client/models/tac_range'
require 'ran-core-5g-client/models/tai'
require 'ran-core-5g-client/models/tai_range'
require 'ran-core-5g-client/models/target_area'
require 'ran-core-5g-client/models/tnap_id'
require 'ran-core-5g-client/models/traffic_descriptor'
require 'ran-core-5g-client/models/transport_protocol'
require 'ran-core-5g-client/models/twap_id'
require 'ran-core-5g-client/models/ueid_ext'
require 'ran-core-5g-client/models/ue_access_behavior_report_item'
require 'ran-core-5g-client/models/ue_in_area_filter'
require 'ran-core-5g-client/models/ue_location_trends_report_item'
require 'ran-core-5g-client/models/ue_reachability'
require 'ran-core-5g-client/models/ue_type'
require 'ran-core-5g-client/models/user_location'
require 'ran-core-5g-client/models/utra_location'
require 'ran-core-5g-client/models/var_rep_period'

# APIs
require 'ran-core-5g-client/api/individual_subscription_document_api'
require 'ran-core-5g-client/api/subscriptions_collection_collection_api'

module Core5g
  class << self
    # Customize default settings for the SDK using block.
    #   Core5g.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
