# frozen_string_literal: true

# #Namf_EventExposure
#
# AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
#
# The version of the OpenAPI document: 1.3.0-alpha.3
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.1.0-SNAPSHOT
#

require 'cgi'

module Core5g
  class SubscriptionsCollectionCollectionApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Namf_EventExposure Subscribe service Operation
    # @param amf_create_event_subscription [AmfCreateEventSubscription]
    # @param [Hash] opts the optional parameters
    # @return [AmfCreatedEventSubscription]
    def create_subscription(amf_create_event_subscription, opts = {})
      data, _status_code, _headers = create_subscription_with_http_info(amf_create_event_subscription, opts)
      data
    end

    # Namf_EventExposure Subscribe service Operation
    # @param amf_create_event_subscription [AmfCreateEventSubscription]
    # @param [Hash] opts the optional parameters
    # @return [Array<(AmfCreatedEventSubscription, Integer, Hash)>] AmfCreatedEventSubscription data, response status code and response headers
    def create_subscription_with_http_info(amf_create_event_subscription, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SubscriptionsCollectionCollectionApi.create_subscription ...'
      end
      # verify the required parameter 'amf_create_event_subscription' is set
      if @api_client.config.client_side_validation && amf_create_event_subscription.nil?
        raise ArgumentError,
              "Missing the required parameter 'amf_create_event_subscription' when calling SubscriptionsCollectionCollectionApi.create_subscription"
      end

      # resource path
      local_var_path = '/subscriptions'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'application/problem+json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      header_params['Content-Type'] = content_type unless content_type.nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(amf_create_event_subscription)

      # return_type
      return_type = opts[:debug_return_type] || 'AmfCreatedEventSubscription'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['oAuth2ClientCredentials']

      new_options = opts.merge(
        operation: :'SubscriptionsCollectionCollectionApi.create_subscription',
        header_params:,
        query_params:,
        form_params:,
        body: post_body,
        auth_names:,
        return_type:
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SubscriptionsCollectionCollectionApi#create_subscription\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end
  end
end
